### PR TITLE
Fix DB update to autopopulate stsim_Resolution table

### PR DESCRIPTION
**Pull request by katieb1**
@alexembrey can you confirm that this is correct?

When I look in SQLite studio, the ResolutionId column values are 1 & 2. I'm not sure if this is what we want because aren't the project ID values for all datasheets in the library taken into account when determining a project ID? Is there an easy way to get these values?

### CODE REVIEW

**Comment by katieb1** [comment]
Tested this and it seems to be working, although if you are loading a library that was built with 4.1.0, then you need to manually change the stsim_Resolution table in SQLite Studio to rename the "Resolution" column to the "Name" column and add an "Id" column that has a value of 0 for Base and 1 for Fine. See screenshot for example. 
image

@christopher-givelas and @alexembrey can you test and merge if it looks ok to you?

**Comment by christopher-givelas** [comment]
> Tested this and it seems to be working, although if you are loading a library that was built with 4.1.0, then you need to manually change the stsim_Resolution table in SQLite Studio to rename the "Resolution" column to the "Name" column and add an "Id" column that has a value of 0 for Base and 1 for Fine. See screenshot for example. image
> 
> @christopher-givelas and @alexembrey can you test and merge if it looks ok to you?

It seems like it is working for non 4.1.0 libraries, as mentioned @katieb1.

On a related note, the fact that this doesn't work with libraries that were already at 4.1.0 is a bit disconcerting. I feel like our DB Updates should be treated as immutable so that no matter what version a package is at within a library, it can run the DB update process and grab new fixes. This would entail us never changing a DB Update function that has already been merged into a released version of SyncroSim, and probably extra overhead to in coding complexity to undo the unwanted changes made by previous DB Update versions, but would prevent situations like this versioning problem from happening.

In it's current form, DB updates are only triggered on Minor version bumps (if I'm remembering correctly), which is not ideal. I'm wondering if there is anything preventing us to allow Patch versions to trigger DB Updates @alexembrey?

Also, sorry I've been on this immutability crusade recently lol.

**Comment by katieb1** [comment]
@christopher-givelas I think that's definitely the case for released versions of the package. I didn't make the minor version bump because 
1. ST-Sim v4.1.0 hasn't been released yet , so I think it would be weird to jump from 4.0.0 to 4.2.0; and 
2. Only the libraries that we have been using internally will need to be updated manually (which is like 2 libraries)

**Comment by alexembrey** [comment]
Sorry, I haven't had time to look at this until now...

The DB Update mechanism is triggered when you increment either the Major or Minor version. The Build version does not trigger a DB Update so you can make code changes without triggering a DB Update. For example, you might just need to change some menu text and so this should not trigger a DB Update.

Katie is correct here in that since the packages involved have not shipped it's not a problem to fix up a few internally used libraries manually. This is not ideal, but it also needs to be understood that you should not do production work with an unreleased package, especially if it involves a DB Update. So even if people internal to Apex have been using ST-Sim 4.1.0, they should just be using it for testing with the expectation that any libraries they upgrade might have to be discarded.

However, once a Package has been released, immutability is the law of the land. Specifically, if a bug is found in an already released DB Update then it needs to be corrected with another DB Update. Because of this, DB Updates need to be tested thoroughly because you don't get a second chance. 

There's been some increasing talk about creating an automated test suite for SyncroSim lately, and one area that could use a test suite is DB updates. For example, every DB Update should be able to go from a very old version of a 2.5 Library as well as from the last v3 Library. It sure would be great if you could just run a test script that does a bunch of these types of updates and then does a model run for example.

**Comment by christopher-givelas** [comment]
@katieb1 @alexembrey Thank you both for the clarification, and sorry to be pedantic about this. Being the new SyncroSim developer on the block, I'm still getting up to speed on our practices. Manually adjusting libraries used for internal testing is fine with me. 👍

**Review by christopher-givelas — APPROVED** [review]

**Comment by katieb1** [comment]
@christopher-givelas don't apologize, it's good to be pedantic!

**Pull request merged**
